import ts from 'typescript';import fs from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const dir=path.resolve('.sites-runtime/backend-tests');fs.mkdirSync(dir,{recursive:true});for(const file of ['store','actions','state','files']){const source=fs.readFileSync('lib/server/'+file+'.ts','utf8').replaceAll("from './store'","from './store.mjs'");fs.writeFileSync(dir+'/'+file+'.mjs',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText)}
const {action}=await import(pathToFileURL(dir+'/actions.mjs'));const {state}=await import(pathToFileURL(dir+'/state.mjs'));const {upload,download,report}=await import(pathToFileURL(dir+'/files.mjs'));
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('drizzle/0000_flaky_wrecking_crew.sql','utf8'));sqlite.exec('PRAGMA foreign_keys=ON');
class Statement{constructor(sql,args=[]){this.sql=sql;this.args=args;}bind(...args){return new Statement(this.sql,args)}async first(){return sqlite.prepare(this.sql).get(...this.args)||null}async all(){return {results:sqlite.prepare(this.sql).all(...this.args)}}async run(){const r=sqlite.prepare(this.sql).run(...this.args);return {success:true,meta:{changes:Number(r.changes)}}}}
const objects=new Map();const env={DB:{prepare:sql=>new Statement(sql),async batch(statements){sqlite.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}},BUCKET:{async put(k,stream){const bytes=await new Response(stream).arrayBuffer();objects.set(k,bytes)},async delete(k){objects.delete(k)},async get(k){const bytes=objects.get(k);return bytes?{body:new Blob([bytes]).stream(),size:bytes.byteLength}:null}}};
const owner={userId:'test-owner',email:'owner@example.test',displayName:'Owner'},a={userId:'test-buyer-a',email:'a@example.test',displayName:'Buyer A'},b={userId:'test-buyer-b',email:'b@example.test',displayName:'Buyer B'},outsider={userId:'outsider',email:'owner@example.test',displayName:'Impostor'};
const act=(who,actionName,input={})=>action(env,who,{action:actionName,...input});
const rejects=async(fn,code)=>{await assert.rejects(fn,e=>e.code===code||e.message===code,code)};
assert((await state(env,owner)).setup);await act(owner,'setup',{name:'Test Developer'});await rejects(()=>act(outsider,'setup',{name:'Attacker'}),'ALREADY_SETUP');
const admin=(await state(env,owner)).me;const project=(await act(owner,'project.create',{name:'Project',location:'Dubai',handover:'Q4 2027'})).id;
const createUnit=code=>act(owner,'unit.create',{projectId:project,code,floor:'12',bedrooms:2,area:1181,price:200000000});const ua=(await createUnit('A-1204')).id,ub=(await createUnit('A-1205')).id;
const ia=await act(owner,'buyer.create',{name:'Buyer A',email:a.email}),ib=await act(owner,'buyer.create',{name:'Buyer B',email:b.email});await act(owner,'unit.assign',{unitId:ua,buyerId:ia.id});await act(owner,'unit.assign',{unitId:ub,buyerId:ib.id});
await act(a,'claim',{token:ia.inviteToken});await act(b,'claim',{token:ib.inviteToken});await rejects(()=>act(outsider,'claim',{token:ia.inviteToken}),'INVITE_INVALID');assert((await state(env,outsider)).invitationRequired);
assert.equal((await state(env,a)).units.length,1);assert.equal((await state(env,a)).units[0].id,ua);await rejects(()=>act(a,'unit.create',{projectId:project,code:'HACK',floor:'1',bedrooms:1,area:100,price:100}),'FORBIDDEN');await rejects(()=>act(a,'request.create',{unitId:ub,type:'general',title:'Leak',body:'Forbidden access'}),'NOT_FOUND');
const bill=(await act(owner,'installment.create',{unitId:ua,label:'Booking',amount:10000000,due:'2026-12-31'})).id;await rejects(()=>act(owner,'installment.create',{unitId:ua,label:'Too much',amount:200000000,due:'2026-12-31'}),'PLAN_EXCEEDS_PRICE');
const pay=(await act(a,'payment.create',{unitId:ua,installmentId:bill,amount:10000000,reference:'BANK-123'})).id;await rejects(()=>act(a,'payment.create',{unitId:ua,installmentId:bill,amount:1,reference:'duplicate'}),'PAYMENT_EXCEEDS_DUE');await rejects(()=>act(owner,'payment.review',{id:pay,status:'approved',note:'Checked'}),'PROOF_REQUIRED');
const ap=(await state(env,a)).me,bp=(await state(env,b)).me;
const uploadFile=async(p,kind,target,unitId='')=>{const f=new FormData();f.set('file',new File(['%PDF-1.4\nTest evidence'], 'proof.pdf',{type:'application/pdf'}));f.set('kind',kind);f.set('targetId',target);f.set('unitId',unitId);return upload(env,p,new Request('https://app.test/upload',{method:'POST',body:f}))};
const proof=(await uploadFile(ap,'payment',pay)).id;await rejects(()=>download(env,bp,proof,new Request('https://app.test/file')),'NOT_FOUND');assert.equal((await download(env,ap,proof,new Request('https://app.test/file'))).status,200);await act(owner,'payment.review',{id:pay,status:'approved',note:'Bank transfer verified'});await rejects(()=>act(owner,'payment.review',{id:pay,status:'approved',note:'Duplicate'}),'ALREADY_REVIEWED');assert.equal((await state(env,a)).payments.filter(p=>p.status==='approved').reduce((s,p)=>s+p.amount,0),10000000);assert((await (await report(env,ap,'receipt',pay)).text()).includes('100,000'));await rejects(()=>report(env,bp,'receipt',pay),'NOT_FOUND');
const req=(await act(a,'request.create',{unitId:ua,type:'general',title:'Question',body:'Please confirm the handover date.'})).id;await uploadFile(ap,'request',req);await act(owner,'request.reply',{id:req,body:'We will confirm shortly.'});await act(owner,'request.status',{id:req,status:'processing'});assert.equal((await state(env,a)).messages.length,1);assert.equal((await state(env,b)).messages.length,0);
const projectUpdate=(await act(owner,'update.create',{projectId:project,unitId:null,title:'Monthly update',body:'Structure complete',progress:80,stage:'structure'})).id;const privateUpdate=(await act(owner,'update.create',{projectId:project,unitId:ua,title:'Private apartment update',body:'Unit details',progress:60,stage:'mep'})).id;const privateFile=(await uploadFile(admin,'update',privateUpdate)).id;assert.equal((await state(env,b)).updates.length,1);assert.equal((await state(env,b)).updates[0].id,projectUpdate);await rejects(()=>download(env,bp,privateFile,new Request('https://app.test/file')),'NOT_FOUND');
const snag=(await act(a,'snag.create',{unitId:ua,title:'Window scratch',body:'Scratch on the frame',location:'Living room'})).id;await uploadFile(ap,'snag',snag);await act(owner,'handover.save',{unitId:ua,keys:true,meters:true,documents:true,notes:'Ready'});await rejects(()=>act(a,'handover.sign',{unitId:ua,name:'Buyer A',consent:true}),'SNAGS_OPEN');await act(owner,'snag.status',{id:snag,status:'resolved',resolution:'Frame replaced'});await rejects(()=>act(owner,'snag.status',{id:snag,status:'accepted'}),'BUYER_CONFIRMATION_REQUIRED');await act(a,'snag.status',{id:snag,status:'accepted'});
const slot=(await act(owner,'slot.create',{unitId:ua,start:'2028-01-01T06:00:00.000Z'})).id;await act(a,'slot.book',{id:slot});await rejects(()=>act(a,'slot.book',{id:slot}),'SLOT_UNAVAILABLE');await act(owner,'slot.confirm',{id:slot});await act(a,'handover.sign',{unitId:ua,name:'Buyer A',consent:true});assert((await report(env,ap,'handover',ua)).status===200);await rejects(()=>act(owner,'handover.save',{unitId:ua,keys:false,meters:false,documents:false,notes:'Alter record'}),'HANDOVER_SIGNED');
const task=(await act(owner,'task.create',{unitId:ua,title:'Review payment plan',due:'2026-12-31'})).id;await act(a,'task.status',{id:task,status:'done'});assert.equal((await state(env,a)).tasks[0].status,'done');
await act(owner,'buyer.active',{id:ia.id,active:false});await rejects(()=>act(a,'request.create',{unitId:ua,type:'general',title:'Blocked',body:'Should fail'}),'INVITATION_REQUIRED');assert((await state(env,a)).invitationRequired);await act(owner,'buyer.active',{id:ia.id,active:true});assert.equal((await state(env,a)).units.length,1);
console.log('PASS: identity-bound invitations, role checks, two-buyer isolation, file authorization, payment approval and duplicate protection, project/unit updates, request replies, tasks, snag confirmation, appointment booking, immutable handover, blocking and reactivation.');
